import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Toaster from "@/components/Toaster";
import Providers from '@/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CARNEWS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar></NavBar>
          <div>
            <main className={inter.className}>{children}</main>
          </div>
          <Footer></Footer>
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
